import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function Deploy() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Deploy an App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
               Deploy an App
                </h1>

                <div className={styles.grid}>
                    <a href="/GUI" className={styles.card}>
                        <h2>GUI &rarr;</h2>
                        <p>I want to deploy using a UI with Buttons</p>
                    </a>

                    <a href="/CLI" className={styles.card}>
                        <h2>CLI &rarr;</h2>
                        <p>I want to deploy using a Command Line...</p>
                    </a>
                </div>
            </main>
        </div>
    );
}